### ISSUE TITLE
Config validation failed (mismatched version?)

### ISSUE THREAD

**Issue by BioinfoTongLI** [haniffalab/sci-spatial-data#27]
This error shows up when loading the vitessce interface.
```
Config validation failed

Unknown config version.
```
Assumption: latest config file verison not compatible with the version of vitessce hosted on hindlimb s3?
@dannda @davehorsfall any ideas? Should we just update the vitessce on that s3?

**Comment by dannda** [comment]
Yes, we should update the vitessce on the s3. It is an annoying error because it is a compatible config file, just lowering the version number would make it work.
But @davehorsfall did mention to me just yesterday that it is a pretty old vitessce version on the s3 because it comes from our fork and not from our webapp repo so we should change that.

**Comment by BioinfoTongLI** [comment]
Solved by updating the vitessce app. Closing this
